baseURL = "https://allangcruz.com"
languageCode = "pt-br"
title = "AllanGCruz"
theme = "soho"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Allan Gonçalves da Cruz"
description = "Blog do Allan com conteúdo, estudos, lembretes e comandos"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.jpg"

copyright = "Allan Gonçalves da Cruz"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

disable_share = false

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/allangcruz"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/allangcruz"

[[params.socialIcons]]
icon = "fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/allangcruz"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/allangcruz"

[menu]
[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Sobre"
identifier = "sobre"
weight = 200
url = "/sobre/"

[[menu.main]]
name = "Política de Privacidade"
identifier = "politica-de-privacidade"
weight = 300
url = "/politica-de-privacidade/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4